### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Ronningen** [andiva/tmpnn#1]
- [x] early stopping
- [x] weights optimisation due to symmetries
- [x] regularisation support
- [x] regularisation optimisation
- [x] learnable initial target values
- [x] latent units
- [ ] scheduler
- [ ] freeze weights
- [ ] explore sufficient epochs dependence from number of parameters
- [x] classification
- [ ] time sireas
- [ ] automl
- [x] boosting
